name: Feature request
description: An idea for GravitiOS
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What would you like to do from your phone?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: How do you picture it?
