#!/bin/sh
# Generates the Swift types for the wire contract from the vendored protos
# (ADR-001): buf (pinned in package.json) with Apple's swift-protobuf plugin,
# pinned in contract/buf.gen.yaml to the runtime version in the Xcode project.
# Never edit TheHermes/Core/Generated by hand.
#
#   scripts/contract/generate-swift.sh          regenerate TheHermes/Core/Generated
#   scripts/contract/generate-swift.sh --check  fail if a vendored file was edited by hand, or the
#                                               committed Swift differs from the protos (CI runs this)
set -eu
cd "$(dirname "$0")/../.."
out=TheHermes/Core/Generated
buf=scripts/contract/node_modules/.bin/buf

[ -x "$buf" ] || npm ci --prefix scripts/contract --no-audit --no-fund >/dev/null

[ "${1:-}" = "--check" ] && scripts/contract/vendor.sh --check

rm -rf "$out"
(cd contract && "../$buf" generate)

if [ "${1:-}" = "--check" ]; then
  if [ -n "$(git status --porcelain -- "$out")" ]; then
    git status --short -- "$out" >&2
    echo "$out is out of date with contract/proto. Run scripts/contract/generate-swift.sh and commit." >&2
    exit 1
  fi
  echo "$out is up to date with contract/proto."
else
  echo "Wrote $out."
fi
