#!/bin/sh
# Generates the Swift types for the board wire contract from the vendored
# JSON Schema (H-020 §1.4). The schema is the source of truth; never edit the
# generated file by hand.
#
#   scripts/contract/generate-swift.sh          regenerate TheHermes/Core/Generated/Board.swift
#   scripts/contract/generate-swift.sh --check  fail if it is out of date with the schema
set -eu
cd "$(dirname "$0")/../.."
schema=contract/board.schema.json
out=TheHermes/Core/Generated/Board.swift
quicktype=scripts/contract/node_modules/.bin/quicktype

[ -x "$quicktype" ] || npm ci --prefix scripts/contract --no-audit --no-fund >/dev/null

version=$(sed -n 's/.*"x-contract": *{"name": *"board", *"version": *\([0-9]*\)}.*/\1/p' "$schema")
[ -n "$version" ] || version=$(python3 -c "import json,sys; print(json.load(open('$schema'))['x-contract']['version'])")

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
{
  echo "// Generated by scripts/contract/generate-swift.sh from $schema"
  echo "// (board contract v$version). Do not edit: change the schema and regenerate."
  echo
  # Types are prefixed so generic names (Item, Size, Role) stay out of the
  # app's namespace; "BoardBoard…" from types already named Board… collapses.
  "$quicktype" --src-lang schema --lang swift --top-level BoardContract --type-prefix Board \
    --struct-or-class struct --access-level internal --no-initializers --acronym-style pascal \
    "$schema" | sed -e 's/BoardBoard/Board/g' -e '/^\/\/ This file was generated from JSON Schema using quicktype/d'
} > "$tmp"

if [ "${1:-}" = "--check" ]; then
  if ! cmp -s "$tmp" "$out"; then
    echo "$out is out of date with $schema. Run scripts/contract/generate-swift.sh." >&2
    exit 1
  fi
  echo "$out is up to date (board v$version)."
else
  mkdir -p "$(dirname "$out")"
  cp "$tmp" "$out"
  echo "Wrote $out (board v$version)."
fi
